name: check_readiness

on:
  workflow_dispatch: {}
  schedule:
    - cron: "15 9 * * *"   # runs daily at 09:15 UTC

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: pip install requests
      - name: Run readiness check
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          UPTIME_MIN: "75"   # temporary bootstrap threshold
        run: python scripts/check_readiness.py
