name: Symbolic Logger (Daily, ET-aware)

on:
  schedule:
    # Run every hour at :05; Python decides whether it's 09:05 ET.
    - cron: "5 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  log_symbolic_heartbeat:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Append daily entry (only at 09:05 ET)
        id: append
        run: |
          python - << 'PYCODE'
          import json, sys
          from pathlib import Path
          from datetime import datetime, timezone
          try:
              from zoneinfo import ZoneInfo
              now_et = datetime.now(ZoneInfo("America/New_York"))
          except Exception:
              now_et = datetime.utcnow().replace(tzinfo=timezone.utc)

          # Only proceed at 09:05 ET (once per day)
          if not (now_et.hour == 9 and now_et.minute == 5):
              print("Skip: not 09:05 ET")
              sys.exit(0)

          log_path = Path("data/logs/symbolic_log.json")
          log_path.parent.mkdir(parents=True, exist_ok=True)

          if log_path.exists():
              text = log_path.read_text().strip()
              if text.startswith("{"):
                  data = json.loads(text)
                  entries = data.get("entries", [])
                  schema = "dict"
              else:
                  entries = json.loads(text)
                  schema = "list"
          else:
              entries = []
              schema = "dict"

          ts_utc = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
          entry = {
              "ts": ts_utc,
              "symbol": "heartbeat",
              "resonance": False,
              "notes": "daily auto-log",
              "source": "github-actions"
          }
          entries.append(entry)

          payload = {"entries": entries} if schema == "dict" else entries
          log_path.write_text(json.dumps(payload, indent=2))
          print(f"Appended entry at {ts_utc}")
          PYCODE

      - name: Commit & push log (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/logs/symbolic_log.json
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "logger: append symbolic_log.json [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
